import type { AppearanceHostSources } from '../../src/appearance-profile'
import type { EditorConfiguration, HostMessage, Result, WebviewMessage } from '../../src/protocol'
import { contentHash } from '../../src/protocol'
import { defaultPerwriteSettings } from '../../src/settings-resolver'
import { EditorView } from '@codemirror/view'

const outbound: WebviewMessage[] = []
Object.assign(globalThis, { acquireVsCodeApi: () => ({ postMessage(message: WebviewMessage) { outbound.push(message) }, getState() { return undefined }, setState() {} }) })
document.documentElement.style.setProperty('--vscode-editor-background', '#123456')
document.documentElement.style.setProperty('--vscode-editor-foreground', '#abcdef')
document.body.dataset.vscodeThemeKind = 'vscode-dark'
await import('../../webview/index')
const appearance: AppearanceHostSources = { version: 1, settings: { ok: true, value: { perwrite: defaultPerwriteSettings(), editorFont: { family: 'Mono', size: 14 } } }, fallbackFont: { family: 'Mono', size: 14 }, tokenTheme: { ok: true, value: { name: 'sample', type: 'dark', tokenColors: [], semanticTokenColors: {}, semanticHighlighting: false } } }
const configuration: Result<EditorConfiguration> = { ok: true, value: { defaultViewMode: 'rich', configurationFailure: null, rendering: { generation: 1, codeBlockWrap: true, mermaidLayout: 'elk', mermaidMaxEdges: 1024, mermaidPanStep: 80, mermaidZoomStep: 1.5, texRendering: true } } }
const uri = 'file:host-scenario'; let generation = 0; let content = '# Title\n'; let selection: number[] = []
function sendSnapshot(externalChange: string | null = null) { window.dispatchEvent(new MessageEvent('message', { data: { type: 'draft-snapshot', uri, content, contentHash: contentHash(content), selection, generation, dirty: content !== '# Title\n', externalChange } satisfies HostMessage })) }
Object.assign(globalThis, { perwriteHost: { outbound, sendInit() { window.dispatchEvent(new MessageEvent('message', { data: { type: 'init', documentId: uri, content, documentVersion: generation, appearance, baseResourceUri: 'https://perwrite.test/', configuration } satisfies HostMessage })) }, sendSnapshot, undo() { content = '# Title\n'; selection = [1, 0]; generation++; sendSnapshot() }, redo() { content = '# Title\nA'; selection = [8, 7]; generation++; sendSnapshot() }, externalClean(value: string) { content = value; selection = []; generation++; sendSnapshot() }, externalDirty(value: string) { generation++; sendSnapshot(value) }, rejectCanonical(value: string) { content = value; selection = [0, 0]; generation++; sendSnapshot() }, select(anchor: number, head: number) { const editor = document.querySelector<HTMLElement>('.cm-editor'); const view = editor && EditorView.findFromDOM(editor); if (!view) throw new Error('editor unavailable'); view.dispatch({ selection: { anchor, head } }) }, input(value: string) { const editor = document.querySelector<HTMLElement>('.cm-editor'); const view = editor && EditorView.findFromDOM(editor); if (!view) throw new Error('editor unavailable'); view.dispatch({ changes: { from: view.state.doc.length, insert: value } }) }, toggle() { document.querySelector<HTMLButtonElement>('#toggle-view')?.click() }, witness() { const editor = document.querySelector<HTMLElement>('.cm-editor'); const view = editor && EditorView.findFromDOM(editor); return { content: view?.state.doc.toString(), selection: view?.state.selection.ranges.flatMap(range => [range.anchor, range.head]), generation: document.body.dataset.webviewSessionGeneration, dirty: document.body.dataset.dirty, conflict: document.body.dataset.externalConflict, outbound: outbound.slice() } } } })
