import { runBrowserTest } from './harness.mjs'

await runBrowserTest({
  prefix: 'perwrite-webview-', entryPoint: 'tests/browser/host-scenario.ts', outfile: 'host.js', format: 'esm', target: 'es2022',
  html: '<!doctype html><html><body><div id="toolbar"><button id="toggle-view">Render</button><button id="toggle-diff">Diff</button></div><div id="editor"></div><script type="module" src="/host.js"></script></body></html>', viewport: { width: 1000, height: 800 },
  async run(page, { check }) {
    await page.waitForFunction(() => globalThis.perwriteHost?.outbound.some(message => message.type === 'ready'))
    await page.evaluate(() => globalThis.perwriteHost.sendInit())
    await page.waitForSelector('.cm-editor')
    const initial = await page.evaluate(() => globalThis.perwriteHost.witness())
    check('初期 snapshot で EditorView を一度だけ構築する', initial.content === '# Title\n')
    await page.evaluate(() => globalThis.perwriteHost.input('A'))
    await page.waitForFunction(() => globalThis.perwriteHost.outbound.some(message => message.type === 'draft-edit'))
    const edit = await page.evaluate(() => globalThis.perwriteHost.outbound.findLast(message => message.type === 'draft-edit'))
    check('実入力は draft-edit を送る', edit?.changes?.[0]?.insert === 'A')
    await page.evaluate(() => { globalThis.perwriteHost.input('B') })
    await page.waitForFunction(() => globalThis.perwriteHost.outbound.filter(message => message.type === 'draft-edit').length === 2)
    const rapid = await page.evaluate(() => globalThis.perwriteHost.outbound.filter(message => message.type === 'draft-edit').slice(-2))
    check('Host snapshot 前の連続入力は連続 generation を送る', rapid[1].generation === rapid[0].generation + 1 && rapid[1].beforeHash !== rapid[0].beforeHash)
    await page.evaluate(() => globalThis.perwriteHost.rejectCanonical('# Canonical\n'))
    await page.waitForFunction(() => globalThis.perwriteHost.witness().content === '# Canonical\n')
    check('拒否後の canonical snapshot は楽観入力を戻す', (await page.evaluate(() => globalThis.perwriteHost.witness())).content === '# Canonical\n')
    await page.evaluate(() => globalThis.perwriteHost.select(3, 1))
    await page.evaluate(() => globalThis.perwriteHost.input('!'))
    await page.waitForFunction(() => globalThis.perwriteHost.outbound.filter(message => message.type === 'draft-edit').at(-1)?.selection?.join(',') === '3,1')
    check('選択範囲は draft-edit として anchor/head 順に送る', (await page.evaluate(() => globalThis.perwriteHost.outbound.filter(message => message.type === 'draft-edit').at(-1)?.selection)).join(',') === '3,1')
    await page.evaluate(() => { globalThis.perwriteHost.redo() })
    await page.waitForFunction(() => globalThis.perwriteHost.witness().content === '# Title\nA')
    const redo = await page.evaluate(() => globalThis.perwriteHost.witness())
    check('Redo snapshot は editor と selection を置換する', redo.content === '# Title\nA' && redo.selection.join(',') === '8,7')
    await page.evaluate(() => { globalThis.perwriteHost.undo() })
    await page.waitForFunction(() => globalThis.perwriteHost.witness().content === '# Title\n')
    const undo = await page.evaluate(() => globalThis.perwriteHost.witness())
    check('Undo snapshot は editor と selection を置換する', undo.content === '# Title\n' && undo.selection.join(',') === '1,0')
    await page.evaluate(() => globalThis.perwriteHost.externalClean('# External\n'))
    await page.waitForFunction(() => globalThis.perwriteHost.witness().content === '# External\n')
    check('clean external snapshot を適用する', (await page.evaluate(() => globalThis.perwriteHost.witness())).content === '# External\n')
    await page.evaluate(() => globalThis.perwriteHost.externalDirty('# Disk\n'))
    const dirty = await page.evaluate(() => globalThis.perwriteHost.witness())
    check('dirty external snapshot は draft を保持して conflict を表示する', dirty.content === '# External\n' && dirty.conflict === 'true')
    await page.evaluate(() => globalThis.perwriteHost.select(4, 2))
    const beforeToggle = await page.evaluate(() => globalThis.perwriteHost.witness())
    await page.evaluate(() => globalThis.perwriteHost.toggle())
    await page.waitForTimeout(20)
    check('表示切替は draft と selection を保持する', await page.evaluate(expected => { const witness = globalThis.perwriteHost.witness(); return witness.content === expected.content && witness.selection.join(',') === expected.selection.join(',') }, beforeToggle))
  },
})
