import type { AppearanceHostSources } from './appearance-profile'
import type { ComparisonFailure, ComparisonResult, EditorConfiguration, GitRevision, HostMessage, ResolvedComparisonSide, ResolvedGitComparison, ResolvedReadonlyDocument, Result, TextChange, WebviewMessage } from './protocol'
import { contentHash, validateSelection, validateTextChanges } from './protocol'
import { MERMAID_SETTING_SCHEMA, PERWRITE_SETTING_SCHEMA, type EditorFontSettings, type PerwriteSettingName, type ResolvedAppearanceSettings } from './settings-resolver'

export interface DecodeFailure { readonly kind: 'invalid-message'; readonly path: string; readonly reason: string }
export type DecodeResult<T> = { ok: true; value: T } | { ok: false; error: DecodeFailure }
export function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null && !Array.isArray(value) }
export function exactKeys(value: Record<string, unknown>, required: readonly string[], optional: readonly string[] = []): boolean { const allowed = new Set([...required, ...optional]); return Object.keys(value).every(key => allowed.has(key)) && required.every(key => key in value) }
function failure(path: string, reason: string): DecodeResult<never> { return { ok: false, error: { kind: 'invalid-message', path, reason } } }
function integer(value: unknown): value is number { return typeof value === 'number' && Number.isInteger(value) && Number.isFinite(value) }
function string(value: unknown): value is string { return typeof value === 'string' && value.length > 0 }
function enumValue<T extends string>(value: unknown, values: readonly T[]): value is T { return typeof value === 'string' && values.includes(value as T) }

function decodeResult<T>(value: unknown, decoder: (value: unknown, path: string) => DecodeResult<T>, path: string): DecodeResult<Result<T>> { if (!isRecord(value) || typeof value.ok !== 'boolean') return failure(path, 'result is invalid'); if (value.ok) { if (!exactKeys(value, ['ok', 'value'])) return failure(path, 'successful result is invalid'); const result = decoder(value.value, `${path}.value`); return result.ok ? { ok: true, value: { ok: true, value: result.value } } : result }; return !exactKeys(value, ['ok', 'error']) || typeof value.error !== 'string' ? failure(path, 'failed result is invalid') : { ok: true, value: { ok: false, error: value.error } } }
function decodeAppearance(value: unknown, path: string): DecodeResult<AppearanceHostSources> { if (!isRecord(value) || !exactKeys(value, ['version', 'settings', 'fallbackFont', 'tokenTheme']) || !integer(value.version) || !isRecord(value.fallbackFont)) return failure(path, 'appearance is invalid'); return { ok: true, value: value as unknown as AppearanceHostSources } }
export function decodeAppearanceSources(value: unknown, path = 'appearance'): DecodeResult<AppearanceHostSources> { return decodeAppearance(value, path) }
export function decodeEditorConfiguration(value: unknown, path = 'configuration'): DecodeResult<EditorConfiguration> { if (!isRecord(value) || !exactKeys(value, ['defaultViewMode', 'rendering', 'configurationFailure']) || !enumValue(value.defaultViewMode, ['raw', 'rich', 'render'] as const) || !isRecord(value.rendering)) return failure(path, 'configuration is invalid'); return { ok: true, value: value as unknown as EditorConfiguration } }
export function decodeGitRevision(value: unknown, path = 'revision'): DecodeResult<GitRevision> { if (!isRecord(value) || typeof value.kind !== 'string') return failure(path, 'revision is invalid'); if ((value.kind === 'working-tree' || value.kind === 'index') && exactKeys(value, ['kind'])) return { ok: true, value: { kind: value.kind } }; if (value.kind === 'commit' && exactKeys(value, ['kind', 'ref']) && string(value.ref)) return { ok: true, value: { kind: 'commit', ref: value.ref } }; return failure(path, 'revision is invalid') }
export function decodeTextChanges(value: unknown, path = 'changes'): DecodeResult<readonly TextChange[]> { if (!Array.isArray(value)) return failure(path, 'changes must be an array'); const changes: TextChange[] = []; for (const entry of value) { if (!isRecord(entry) || !exactKeys(entry, ['from', 'to', 'insert']) || !integer(entry.from) || !integer(entry.to) || typeof entry.insert !== 'string') return failure(path, 'change is invalid'); changes.push({ from: entry.from, to: entry.to, insert: entry.insert }) }; const valid = validateTextChanges(changes); return valid.ok ? { ok: true, value: changes } : failure(path, valid.reason) }
function decodeComparison(value: unknown, path: string): DecodeResult<ResolvedGitComparison> { if (!isRecord(value) || !exactKeys(value, ['identity', 'original', 'modified', 'editableSide'])) return failure(path, 'comparison is invalid'); return { ok: true, value: value as unknown as ResolvedGitComparison } }
function decodeComparisonResult(value: unknown, path: string): DecodeResult<ComparisonResult<ResolvedGitComparison>> { return decodeResult(value, decodeComparison, path) as DecodeResult<ComparisonResult<ResolvedGitComparison>> }

export function decodeHostMessage(value: unknown): DecodeResult<HostMessage> { if (!isRecord(value) || typeof value.type !== 'string') return failure('message', 'message type is required'); if (value.type === 'draft-snapshot') return exactKeys(value, ['type', 'uri', 'content', 'contentHash', 'selection', 'generation', 'dirty', 'externalChange']) && string(value.uri) && typeof value.content === 'string' && value.contentHash === contentHash(value.content) && Array.isArray(value.selection) && validateSelection(value.selection, value.content.length).ok && integer(value.generation) && typeof value.dirty === 'boolean' && (value.externalChange === null || typeof value.externalChange === 'string') ? { ok: true, value: value as HostMessage } : failure('message', 'draft snapshot is invalid'); if (value.type === 'init') { if (!exactKeys(value, ['type', 'documentId', 'content', 'appearance', 'baseResourceUri', 'configuration'], ['documentVersion']) || !string(value.documentId) || typeof value.content !== 'string' || !string(value.baseResourceUri)) return failure('message', 'init is invalid'); const appearance = decodeAppearance(value.appearance, 'appearance'); const configuration = decodeResult(value.configuration, decodeEditorConfiguration, 'configuration'); if (!appearance.ok) return appearance; if (!configuration.ok) return { ok: false, error: configuration.error }; return { ok: true, value: { ...value, appearance: appearance.value, configuration: configuration.value } as HostMessage } }; if (value.type === 'appearance-change') { const appearance = decodeAppearance(value.appearance, 'appearance'); return appearance.ok ? { ok: true, value: { type: 'appearance-change', appearance: appearance.value } } : appearance }; if (value.type === 'configuration-change') { const configuration = decodeResult(value.configuration, decodeEditorConfiguration, 'configuration'); return configuration.ok ? { ok: true, value: { type: 'configuration-change', configuration: configuration.value } } : configuration }; if (value.type === 'reveal-target') return exactKeys(value, ['type', 'documentId', 'from', 'to', 'source']) && string(value.documentId) && integer(value.from) && integer(value.to) && value.from >= 0 && value.to >= value.from && value.source === 'external' ? { ok: true, value: value as HostMessage } : failure('message', 'reveal is invalid'); if (value.type === 'comparison-init' || value.type === 'comparison-result' || value.type === 'readonly-init') return { ok: true, value: value as HostMessage }; return failure('message', 'unknown host message') }

export function decodeWebviewMessage(value: unknown): DecodeResult<WebviewMessage> { if (!isRecord(value) || typeof value.type !== 'string') return failure('message', 'message type is required'); if (value.type === 'draft-edit') { if (!exactKeys(value, ['type', 'uri', 'generation', 'beforeHash', 'changes', 'selection']) || !string(value.uri) || !integer(value.generation) || value.generation < 0 || typeof value.beforeHash !== 'string' || !Array.isArray(value.selection) || value.selection.length % 2 !== 0 || !value.selection.every(value => integer(value) && value >= 0)) return failure('message', 'draft edit is invalid'); const changes = decodeTextChanges(value.changes); return changes.ok ? { ok: true, value: { type: 'draft-edit', uri: value.uri, generation: value.generation, beforeHash: value.beforeHash, changes: changes.value, selection: value.selection } } : changes }; if (value.type === 'ready') return exactKeys(value, ['type']) ? { ok: true, value: { type: 'ready' } } : failure('message', 'ready is invalid'); if (value.type === 'editor-ready') return exactKeys(value, ['type', 'documentIds']) && Array.isArray(value.documentIds) && value.documentIds.every(string) ? { ok: true, value: { type: 'editor-ready', documentIds: value.documentIds } } : failure('message', 'editor ready is invalid'); if (value.type === 'activate-link') return exactKeys(value, ['type', 'documentId', 'destination']) && string(value.documentId) && string(value.destination) ? { ok: true, value: { type: 'activate-link', documentId: value.documentId, destination: value.destination } } : failure('message', 'link is invalid'); if (value.type === 'comparison-request') { const original = decodeGitRevision(value.original, 'original'); const modified = decodeGitRevision(value.modified, 'modified'); return exactKeys(value, ['type', 'requestId', 'original', 'modified']) && integer(value.requestId) && original.ok && modified.ok ? { ok: true, value: { type: 'comparison-request', requestId: value.requestId, original: original.value, modified: modified.value } } : failure('message', 'comparison request is invalid') }; return failure('message', 'unknown webview message') }

export type { ComparisonFailure, ResolvedComparisonSide, ResolvedReadonlyDocument, EditorFontSettings, PerwriteSettingName, ResolvedAppearanceSettings }
export { MERMAID_SETTING_SCHEMA, PERWRITE_SETTING_SCHEMA }
